### ISSUE TITLE
Can figure out of an unselect node with green dotted line

### ISSUE THREAD

**Issue by hsauro** [evilnose/PyRKViewer#11]
I got into a state where I couldn't remove the green dotted line around a node.  After I pressed all the buttons I found the hitting products removed it. However, there should be an easier way to unselect this, for example:

1. User hits escape key and dotted lines disappear
2. User clicks on an empty canvas area and dotted lines disappear

At the moment it's difficult to get out of this mode unless you know what you're doing.

**Comment by evilnose** [comment]
implemented first solution.
