### ISSUE TITLE
Uses should be able to place the text in nodes out ide a node to mimic the escher style

### ISSUE THREAD

**Issue by hsauro** [evilnose/PyRKViewer#115]
Users should be able to place the text currently in nodes outside a node to mimic the Escher style:

![image](https://user-images.githubusercontent.com/1054990/125701533-4f50aa32-83bb-49a7-8ef3-8b17998355ac.png)

**Comment by samuels342** [comment]
Users can now choose to display text inside, above, next to, or below nodes. Left\right position of the text is determined by text alignment choice.
