### ISSUE TITLE
When a user selects a circle for a shape, it should be a ciricle that is displayed not an ellipse

### ISSUE THREAD

**Issue by hsauro** [evilnose/PyRKViewer#117]
When a user selects a circle for a shape, currently what is shown is an ellipse. By default make the selection of a circle show a circle on the canvas. In the image below, on the left is the current display, on the right is what we'd like it to actually look like. 

![image](https://user-images.githubusercontent.com/1054990/125701813-54595010-0b3b-4f72-94cc-c97ca7930427.png)

**Comment by samuels342** [comment]
Resolved by updates to forms.py
