### ISSUE TITLE
Add compartments to the application

### ISSUE THREAD

**Issue by hsauro** [evilnose/PyRKViewer#3]
Allow users to add and delete compartments. These are just rounded rectangle boxes with stroke and fill colors as well as edge (stroke) thickness.  Other properties include an Id and a volume (double value, default to 1.0). Compartments can be resized.  Compartments may overlap or even appear to be inside another compartment, however this is just a visual effect, in the object model, compartment won't be allowed to be inside compartments 

Compartments can be moved. Nodes that are moved into a compartment become part of the compartment and vice versa. A compartment can be moved over nodes and nodes become part of the compartment. When I compartment is moved, any nodes and reactions in the compartment will also move with the compartments. Compartments will have their own property sheet.

**Comment by evilnose** [comment]
Compartments have been added with basic operations, including adding, moving, tranferring nodes, etc. However, a few additional core features have not been implemented yet; they are documented here:
* Delete compartments
* Compartment form for editing
* Minor issue when resizing compartments: right now we want to enforce the constraint that nodes in a compartment must be drawn entirely within the bounds of that compartment. However, now when one resizes a compartment, the compartment itself may become smaller than the nodes in it. Need to implement a fix for this.
