### ISSUE TITLE
Exception handler arround a plugin call

### ISSUE THREAD

**Issue by hsauro** [evilnose/PyRKViewer#83]
There should be an exception handler around a plugin call so that if the plugin crashes it doesn't pull the entire application down.

**Comment by evilnose** [comment]
Thought I solved this using a global error catcher and checking if the origin is a plugin, but clearly this didn't work. By exiting the main application loop and "rejoining", unpredictable errors show up.

The only way to implement this is to catch the exception from the plugin manager.
